spring:
  application:
    name: template

  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false # spring.jpa.open-in-view が暗黙的に有効になっているため、明示的に無効化
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

jwt:
  private-key-path: keys/private_key.pem
  public-key-path: keys/public_key.pem
